-- MySQL Script generated by MySQL Workbench
-- qua 21 nov 2018 21:31:21 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ereciclar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ereciclar` ;

-- -----------------------------------------------------
-- Schema ereciclar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ereciclar` DEFAULT CHARACTER SET utf8 ;
USE `ereciclar` ;

-- -----------------------------------------------------
-- Table `ereciclar`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ereciclar`.`location` ;

CREATE TABLE IF NOT EXISTS `ereciclar`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `zipcode` VARCHAR(15) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `number` VARCHAR(10) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  `additional` VARCHAR(50) NULL,
  `latitude` VARCHAR(20) NULL,
  `longitude` VARCHAR(20) NULL,
  `type` ENUM('COLLECTOR_MAN', 'COLLECTOR_COMPANY', 'DISCARD_POINT', 'DONATION') NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ereciclar`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ereciclar`.`user` ;

CREATE TABLE IF NOT EXISTS `ereciclar`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `location_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `picture` VARCHAR(255) NOT NULL,
  `phone` CHAR(14) NULL,
  `cellphone` CHAR(15) NOT NULL,
  `email` VARCHAR(100) NULL,
  `personal_code` VARCHAR(30) NULL,
  `gender` ENUM('F', 'M') NOT NULL,
  `birthday` DATE NOT NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`),
  INDEX `location_id_idx` (`location_id` ASC),
  CONSTRAINT `location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `ereciclar`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ereciclar`.`collector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ereciclar`.`collector` ;

CREATE TABLE IF NOT EXISTS `ereciclar`.`collector` (
  `collector_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('CAR', 'PUSHCAR', 'OTHER', 'NONE') NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`collector_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ereciclar`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ereciclar`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ereciclar`.`category` ;

CREATE TABLE IF NOT EXISTS `ereciclar`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ereciclar`.`collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ereciclar`.`collection` ;

CREATE TABLE IF NOT EXISTS `ereciclar`.`collection` (
  `collection_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `collector_id` INT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`collection_id`),
  INDEX `category_id_idx` (`category_id` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `ereciclar`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ereciclar`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ereciclar`.`request` ;

CREATE TABLE IF NOT EXISTS `ereciclar`.`request` (
  `request_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `collection_id` INT NOT NULL,
  `collector_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `status` ENUM('CREATED', 'ACCEPT', 'FINISH') NOT NULL,
  `scheduled_start` TIME NULL,
  `scheduled_end` TIME NULL,
  `scheduled_at` TIMESTAMP NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL,
  `accept_at` TIMESTAMP NULL,
  PRIMARY KEY (`request_id`),
  INDEX `request_user_id_idx` (`user_id` ASC),
  INDEX `request_collection_id_idx` (`collection_id` ASC),
  INDEX `collector_id_idx` (`collector_id` ASC),
  INDEX `location_id_idx` (`location_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ereciclar`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `collection_id`
    FOREIGN KEY (`collection_id`)
    REFERENCES `ereciclar`.`collection` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `collector_id`
    FOREIGN KEY (`collector_id`)
    REFERENCES `ereciclar`.`collector` (`collector_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `ereciclar`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ereciclar`.`location`
-- -----------------------------------------------------
START TRANSACTION;
USE `ereciclar`;
INSERT INTO `ereciclar`.`location` (`location_id`, `zipcode`, `street`, `number`, `state`, `city`, `country`, `additional`, `latitude`, `longitude`, `type`, `create_at`, `update_at`) VALUES (1, '05773020', 'Rua Bernardo Correia Leitão', '941', 'São Paulo', 'SP', 'Brasil', 'Casa', NULL, NULL, 'COLLECTOR_MAN', DEFAULT, NOW());

COMMIT;


-- -----------------------------------------------------
-- Data for table `ereciclar`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `ereciclar`;
INSERT INTO `ereciclar`.`user` (`user_id`, `location_id`, `name`, `nickname`, `picture`, `phone`, `cellphone`, `email`, `personal_code`, `gender`, `birthday`, `create_at`, `update_at`) VALUES (1, 1, 'Adriano', 'Dri', '', '+5511954976161', '+5511954976161', 'ditec@gmail.com', '30070470804', 'M', NOW(), NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ereciclar`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `ereciclar`;
INSERT INTO `ereciclar`.`category` (`category_id`, `name`) VALUES (1, 'ELECTRONIC');
INSERT INTO `ereciclar`.`category` (`category_id`, `name`) VALUES (2, 'METAL');
INSERT INTO `ereciclar`.`category` (`category_id`, `name`) VALUES (3, 'PLASTIC');

COMMIT;

